### PR TITLE
Add translations for sword/shield abilities and moves

### LINKED ISSUE #27: Move name changes for generation 8
Hello !

First of all, thank you so much for your API. It's super useful ! I noticed some errors about moves names that have been changed in generation 8 (at least in french). I noticed bulbapedia had a page on that so I thought about sharing it to you :

https://bulbapedia.bulbagarden.net/wiki/List_of_modified_moves#French
after "Generation VII to Generation VIII"

All the moves that I checked that changed last generation seems to still be in "gen 7 format". Could you fix that ?

### PR DESCRIPTION
**Pull request by Parnassius**
I put the two scripts I used in `pokeapi/scripts/gen8`, both are based on the files already there.

This should close #27 and #28 as well

### CODE REVIEW

**Comment by Naramsim** [comment]
Thanks a lot! I merged just before a fix for the French language. 

I see this PR brings in more languages, but I'd like to discuss here a bit the Chinese changes.

In my opinion, we need to support a third language.

Right now we have Traditional Chinese and Simplified Chinese. But on Bulbapedia we have three variants: 1 for Cantonese and 2 for Mandarin. Out of those two Mandarin, I suspect one is Traditional Chinese. I have a Chinese friend so I'll try to ask her what we should do here.

**Comment by Naramsim** [comment]
Ok I can confirm, there are three languages.

Cantonese
Mandarin (traditional)
Mandarin (simplified)

Those are presented in the order above on Bulbapedia. So we need to think about how to go on with this PR.

**Comment by Parnassius** [comment]
The problem is sword/shield data files (and sm/usum as well, not sure about let's go) only contain 2 folders, not three. Language id 4 (called Traditional chinese in-game) seems to correspond to Cantonese, and language id 12 (Simplified chinese in-game) to Mandarin traditional in sm/usum and Mandarin simplified in letsgo/sword/shield. For example https://bulbapedia.bulbagarden.net/wiki/Shift_Gear_(move)#In_other_languages seems to confirm this (see the tooltips next to the chinese translations).

Honestly I would simply replace them, since names used in old games are not in the CSVs, and for example abilities didn't change at all, but obviously it's not my call to make

**Comment by Naramsim** [comment]
Ok, let's merge this PR.

**Pull request merged**
