### PR TITLE
Gen8 & Meltan data part 2

### PR DESCRIPTION
**Pull request by myoKun345**
Through testing my application on the staging API, I noticed I forgot to add growth rates, has_gender_differences, and shapes to pokemon_species.csv, base experience to pokemon.csv. Also adds missing stats for meltan/melmetal and corrects base happiness for some DLC pokemon. Comes from Bulbapedia.

Also, something I forgot to mention in my previous PR, I skipped 63 id numbers in pokemon_forms.csv for the numerous cosmetic-only Alcremie forms. This PR additionally fixes that to skip only 62 id numbers (for one default alcremie form at id # 869 and 62 other form id #s).

Sorry I didn't catch this in review! Easy to miss things when I'm just looking at the csv's on Github instead of Excel.

### CODE REVIEW

**Comment by myoKun345** [comment]
Working on adding Galar, Isle of Armor, and Crown Tundra regional dex numbers now, so I've changed this to a draft PR.

**Comment by Naramsim** [comment]
Hi @myoKun345, the data that you added a couple of days ago is now live for everyone. So you can use https://pokeapi.co/api/v2 for reference. I also pushed here the changes I made over at pokeapi so that the two `data` folders are aligned.

Keep in mind that to make everything work at `PokeAPI/pokeapi` I had to introduce some errors in the data. I strongly believe that the data I inputted should follow a different pattern. But at that time I didn't have time to order it properly. 

The commit that introduces wrong data is: https://github.com/PokeAPI/pokeapi/commit/fa4c09675ae5493cc500dd4c7fc6d6bc65c171e3

**Comment by myoKun345** [comment]
Thanks @Naramsim, I have seen that the previous PR is live now. Unfortunately I did not add the experience growth rates to the new pokemon, which is the only feature left blocking my applications from implementing them fully. You are right that the form_order and order fields in PokeAPI/pokeapi@fa4c096 are probably incorrect, but it would indeed take a lot of time to correct and the order numbers are currently not relevant to my use cases for the API.

Anyhow, adding full dex numbers for Sword/Shield and the expansion pass pokedexes took me less time than I thought it would, so I believe this PR is ready for review now. It also includes the new abilities and assigns abilities to all the new pokemon, which should resolve #2 and #13.

Thanks so much for your hard work merging the last PR I submitted! No rush necessary on getting to this one.

**Comment by Naramsim** [comment]
OMG, this is massive, It will take a while to review it a bit decently. I'll try tomorrow.

Big thanks again!

**Review by Naramsim — APPROVED** [review]

**Pull request merged**
