### PR TITLE
update french names for moves, abilities and items according to generation 8 style

### PR DESCRIPTION
**Pull request by pifopi**
Hello !

After opening an issue earlier on, I noticed I could do it myself quite easily. So here is the changes I made.

I used
https://www.pokepedia.fr/Liste_des_%C3%A9l%C3%A9ments_des_jeux_principaux_ayant_chang%C3%A9_de_nom#Noms_chang.C3.A9s_dans_Pok.C3.A9mon_.C3.89p.C3.A9e_et_Bouclier
to be able to get the list of the changes

I also removed space in one file (I think they were unwanted ?)

### CODE REVIEW

**Comment by pifopi** [comment]
#27

**Comment by pifopi** [comment]
Also, I just updated Aegislash stats for 8th generation (150 -> 140). I couldn't find how to search for Aegislash forms so I searched the lines to modify based on existing stats

**Comment by Naramsim** [comment]
Thanks a lot! I'll review these changes when I'll have some time.

**Comment by pifopi** [comment]
You're welcome ! Take your time. Also, I'm not sure if it's automatic or not but once merged, could it be pushed to pokeAPI as well ?

**Review by Naramsim — APPROVED** [review]

**Comment by Naramsim** [comment]
Thanks for the contribution!

**Comment by Naramsim** [comment]
> You're welcome ! Take your time. Also, I'm not sure if it's automatic or not but once merged, could it be pushed to pokeAPI as well ?

I'll bring your changes in PokeAPI as well

**Comment by pifopi** [comment]
Thanks for your work ! Have a nice evening !

**Pull request merged**
